### ISSUE TITLE
Api/GetConsumers fails due JSON serialisation issue

### ISSUE THREAD

**Issue by delixfe** [kuanysh-nabiyev/RabbitMqHttpApiClient#5]
Hi @kuanysh-nabiyev,

requesting consumers currently fails on my test system. Instead of the expected empty object for `Consumer.Arguments` the server sends an empty array.

I have created an issue for that at the management plugin's repo: https://github.com/rabbitmq/rabbitmq-management/issues/424

**Comment by kuanysh-nabiyev** [comment]
@delixfe, may be we just ignore(or remove) Arguments property?

**Comment by delixfe** [comment]
@kuanysh-nabiyev: yes. 

According to the answer from the rabbitmq-management team, this might be the best idea.

**Comment by kuanysh-nabiyev** [comment]
@delixfe fixed

the package version has been incremented

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-management/issues/424 was addressed and will be in RabbitMQ `3.6.11`
